services:
  app:
    image: bloglist-frontend
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.dev.yml"
    ports:
      - 3000:3000
    container_name: bloglist-frontend-dev # This will name the container hello-front-dev
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
